# Сигнатуры для распознавания типов сообщений Telegram, class TgMessagesSigns
[tg_messages_signs]
# Сигнатуры для типа 'vacancy'
tg_vacancy = ["__Subscription:__", "[^ ]Subscription", "__Подписка:__", "Подписка"]
# Сигнатуры для типа 'statistic'
tg_statistic = ["Статистика на Джині за запитом", "Статистика на Djinni за запитом",
    "Статистика на Джинне по запросу", "Statistics on Djinni for the query"]
# Сигнатуры для типа 'service'
tg_service = ["Активные подписки", "Active Subscriptions",
    "Поставил на паузу подписку", "Снял с паузы подписку",
    "Волшебные слова", "Magic words",
    "Новая команда у бота", "Новая команда",
    "Подписку добавил", "Добавить все равно", "__Подсказка__",
    "создания подписки напишите", "Удалил все подписки",
    "/add", "/delete all", "/howmuch", "/help", "/list", "/login", "/pause", "/start",
    "/subscriptions", "/salaries", "/tips_on", "/unpause"]

# Сигнатуры для определения параметров вакансии из текста вакансий Telegram, class TgVacancyTextSigns
[tg_vacancy_text_signs]
# Определение позиции и компании
position_company = [" в "]
# Определение локации и опыта соискателя
location_experience = ["год опыта", "года опыта", "лет опыта",
    "year of experience", "years of experience",
    "Без опыта", "без опыта", "No experience"]
# Определение названия подписки на рассылку
subscription = ["__Subscription:__", "Subscription:", "__Подписка:__", "Подписка:"]
# Определение разделителя между несколькикми вакансиями в одном сообщении
splitter_pattern = ["Subscription", "__Подписка:__", "Подписка"]

# Сигнатуры для определения параметров статистики из текста вакансий Telegram, class TgStatisticTextSigns
[tg_statistic_text_signs]
# Определение количества вакансий за последние 30 дней
vacancies_in_30d = ["Вакансий опубликовано", "Вакансии онлайн", "Вакансій за 30 днів", "Вакансий за 30 дней",
    "Job ads for 30 days", "Jobs for 30 days"]
# Кандидатов онлайн
candidates_online = ["Кандидатов в поиске", "Кандидати онлайн", "Кандидаты онлайн", "Candidates online"]
# Зарплатная вилка
salary = ["Вилка по зарплаті", "Вилка по зарплате", "Salary range"]
# Откликов на одну вакансию
responses_to_vacancies = ["Відгуків на одну вакансію", "Откликов на одну вакансию", "Applications per job posting"]
# Вакансий за неделю
vacancies_per_week = ["Вакансій", "Вакансий", "Jobs"]
# Кандидатов за неделю
candidates_per_week = ["Кандидатів", "Кандидатов", "Candidates"]

# regex_patterns, class RegexPatterns
[regex_patterns]
# URL вакансии на сайте Djinni
url = "https?:\\/\\/djinni.co\\/.*"
# Числовой шаблон
numeric = "([-+]?(?:\\d*[.,]\\d+|\\d+))"
# Числовой шаблон для зарплаты
salary = "\\$?{numeric_pattern}"
# Числовой шаблон для диапазона зарплаты
salary_range = "\\$?{numeric_pattern}-{numeric_pattern}"


# Селекторы для распознавания типов Email сообщений, class EmailMessagesSigns
[email_messages_signs]
# Селекторы для типа 'vacancy'
[[email_messages_signs.vacancy]]
tag = "div"
attr_name = "class"
attr_value = ["card"]
# Селекторы для типа 'vacancy'
[[email_messages_signs.vacancy]]
tag = "td"
attr_name = "style"
attr_value = ["padding-bottom:24px", "box-sizing:border-box"]


# Селекторы для определения параметров вакансии из HTML Email вакансий, class EmailVacancySelVer0 (до 24-01-2025 вкл.)
[email_vacancy_sel_0]
# Селектор позиции и URL
position_url_selector = { tag = "a", attr_name = "style", attr_value = ["font-weight:bold", "font-size:18px"] }
# Селектор названия компании
company_selector = { tag = "span", attr_name = "class", attr_value = ["djinni-whois-expanded"] }
# Селектор локации, опыта, зарплаты
location_experience_salary_selector = { tag = "p", attr_name = "class", attr_value = ["djinni-whois-expanded"] }
# Селектор зарплаты
salary_selector = { tag = "span", attr_name = "style", attr_value = ["color:#4cae4c"] }
# Селектор описания вакансии
job_desc_selector = { tag = "p", attr_name = "style", attr_value = ["margin:5px 0", "color:#333"] }
# Разделитель по селекторам между несколькими вакансиями в одном сообщении
[[email_vacancy_html_sel.splitter_selectors]]
tag = "td"
attr_name = "style"
attr_value = ["padding-bottom:24px"]


# Селекторы для определения параметров вакансии из HTML Email вакансий, class EmailVacancySelVer1 (после 24-01-2025)
[email_vacancy_sel_1]
# Селектор разделитель между несколькими вакансиями в одном сообщении
splitter_selector = { tag = "div", attr_name = "class", attr_value = ["card"] }
# Селектор позиции, URL и зарплаты
position_url_selector = "h3 a"
# Селектор зарплаты
salary_selector = "h3 span"
# Селектор названия компании
company_div_selector = { tag = "div", attr_name = "style", attr_value = ["margin-bottom: 8px"] }
company_span_selector = { tag = "span", attr_name = "class", attr_value = ["details-text"] }
# Селектор опыта, знания языка, типа работы, локации соискателей
experience_lingvo_worktype_location_selector = { tag = "td", attr_name = "class", attr_value = ["details"] }
# Селектор описания вакансии
job_desc_selector = { tag = "p", attr_name = "style", attr_value = ["margin:0", "line-height:1.5"] }
# Селектор подписки
subscription_selector = { tag = "div", attr_name = "class", attr_value = ["djinni-whois-expanded"] }


# Мусорные фрагменты текста для удаления из параметров вакансий, class EmailVacancyJunk
[email_vacancy_junk]
# Удаление лишних подстрок из позиции и компании
company = ["в ", "at "]
# Удаление лишних подстрок из локации и опыта соискателя
experience = ["год опыта", "года опыта", "лет опыта", "Без опыта", "без опыта", "No experience",
    "year of experience", "years of experience", "рік досвіду", "роки досвіду", "років досвіду"]
lingvo = ["-", "–", "Середній", "Вище середнього", "Просунутий"]
# Удаление лишних подстрок из опиасания вакансии
job_desc = ["Подробнее", "Детальніше", "…"]
# Удаление лишних подстрок из названия подписки на рассылку
subscription = ["Subscription:", "Подписка:", "Підписка:"]
